/**
 * The format, published: the JSON Schema a reader can point a validator at, and
 * the field list the `/schema` page renders from it.
 *
 * `design.schema.ts` is the one definition of what a file may be, and it stays
 * the one definition. Nothing here writes a rule down a second time by hand —
 * the document below is generated from that Zod schema, and the table on the
 * page is derived from the generated document, so a field added to the schema
 * appears on the page without anybody remembering to add it.
 *
 * Three decisions are baked into this module and each has a reason worth
 * knowing before changing it.
 *
 * 1. **Generated by Zod itself, with no new dependency.** Zod 4 ships
 *    `z.toJSONSchema`, so the published artifact costs the project nothing
 *    against D7 and D8. It emits draft 2020-12, and D39's blank-string rule
 *    survives as `minLength` plus `pattern`.
 * 2. **Generated for the *input* side, not the output side.** Zod's default
 *    reports the object it hands back, which carries `additionalProperties:
 *    false`. That contradicts D19: a key this schema does not name is ignored,
 *    not rejected, and `{ title, nodes, edges, extra }` really does load. The
 *    default would publish a promise the app does not keep, and an external
 *    validator pointed at it would refuse files this app draws. `io: 'input'`
 *    omits the keyword entirely, so the published file accepts exactly what the
 *    app accepts.
 * 3. **Two rules cannot be published at all, so they are carried in prose.**
 *    Neither of `design.schema.ts`'s refinements survives generation, in any
 *    form — unique node ids and edges naming defined nodes are simply not in
 *    the document. Hand-editing them into the artifact would be the drift this
 *    whole module exists to prevent, so the file stays machine-generated and
 *    `RULES_THE_FILE_CANNOT_STATE` carries them beside it, clearly marked as
 *    rules the file cannot state. D42 already promises users the app works
 *    through their file a pass at a time; a page that left that out would be
 *    quietly less honest than the error panel.
 */

import { z } from 'zod';

import { designSchema } from './design.schema';

/** Any value a JSON document can hold. */
export type JsonValue =
  | string
  | number
  | boolean
  | null
  | readonly JsonValue[]
  | { readonly [key: string]: JsonValue };

/** One JSON object, which is what a JSON Schema document is. */
export interface JsonObject {
  readonly [key: string]: JsonValue;
}

/**
 * Which side of the schema to publish. See rule 2 in the module comment: the
 * output side would publish `additionalProperties: false` and contradict D19.
 */
const PUBLISHED_IO = 'input' as const;

/** One field of a design, as the `/schema` page lists it. */
export interface DesignField {
  /** Where it sits in the file, written the way the error panel writes it. */
  readonly path: string;
  /** Its JSON type, taken from the generated document rather than asserted. */
  readonly type: string;
  /** Whether a file may leave it out. Today nothing may (D19). */
  readonly isRequired: boolean;
  /** What the published document says is allowed in it, in a sentence. */
  readonly rule: string;
  /** What it is for — the one part of the row a person had to write. */
  readonly meaning: string;
}

/** One rule the app enforces that the published file has no way to state. */
export interface DesignRule {
  /** The rule, in a few words, for a heading or a list item. */
  readonly name: string;
  /** Why it exists and what goes wrong without it. */
  readonly detail: string;
}

/**
 * What each field is for.
 *
 * The one hand-written thing in this module, and the only part a generator
 * could not produce: a schema can say `type: "string"` but not what the string
 * is for. Keyed by the path the generated document produces, and checked
 * against it in both directions by `designFields`, so a field added to the
 * schema without a meaning is a loud failure rather than a blank table cell.
 */
const FIELD_MEANINGS: Readonly<Record<string, string>> = {
  title:
    'The name of the design. It heads the drawing, every export, and the name of the exported file.',
  nodes:
    'Every box in the drawing, drawn in the order they are listed. A design with no nodes is valid and draws as an empty picture.',
  'nodes[].id':
    'What edges call this node. It is never drawn — the label is what the box says — and no two nodes may share one.',
  'nodes[].label': 'The words on the box.',
  'nodes[].type':
    'What kind of thing this is. Free text: service, database, queue, external, user and decision each draw as their own silhouette, and so do a handful of aliases for each. Anything else draws as a plain grey dashed box that still carries its label and prints this word under it.',
  edges:
    'Every line in the drawing, drawn in the order they are listed. A design with no edges is valid.',
  'edges[].from': 'The id of the node the arrow leaves.',
  'edges[].to': 'The id of the node the arrow points at.',
  'edges[].label': 'The words on the line.',
};

/**
 * The rules the app enforces that the published file cannot state.
 *
 * Both are cross-field rules, which JSON Schema has no vocabulary for and Zod
 * therefore drops on the way out. They are not optional extras: each is silent
 * corruption of the drawing rather than a visible error, which is why
 * `design.schema.ts` enforces them and why the page has to say so.
 */
export const RULES_THE_FILE_CANNOT_STATE: readonly DesignRule[] = [
  {
    name: 'Every node id is unique',
    detail:
      'Two nodes may not share an id. Without the rule both boxes are drawn, but every edge naming that id lands on whichever box came last — a drawing that is quietly wrong rather than visibly broken.',
  },
  {
    name: 'Every edge names nodes the file defines',
    detail:
      'An edge’s from and to have to be the id of a node in the same file. An edge to a node that is not there has no line to draw and no field to point at.',
  },
];

/**
 * What the app tells a user about the order those two rules are reached in.
 *
 * D20's staging is Zod's and it is right: a rule that reads the whole list of
 * nodes cannot run over a `nodes` that is not yet a list of nodes. D42 turned
 * that into a promise the error panel keeps, and this is the same promise said
 * once on the page that publishes the format.
 */
export const TWO_PASS_NOTE =
  'Those two are checked only once every field above has passed. A file with a bad field and a bad edge is told about the field now and the edge the next time it is loaded, which is why the upload page says what that pass found rather than claiming to list everything at once.';

/**
 * What the published file says about keys it does not name.
 *
 * Worth saying out loud precisely because the document says nothing: there is
 * no `additionalProperties` in it, which is what makes a validator pointed at
 * the file agree with the app instead of being stricter than it.
 */
export const EXTRA_KEYS_NOTE =
  'A key the schema does not name is ignored rather than refused, so a file exported from somewhere else keeps loading. The published file states no additionalProperties, so a validator pointed at it accepts exactly what this app accepts — and the extra keys do not reach the drawing or any export.';

/**
 * The JSON Schema this app publishes, generated from the live Zod schema.
 *
 * @returns a draft 2020-12 document, as plain JSON
 *
 * @example
 * ```typescript
 * publishedDesignSchema().required; // ['title', 'nodes', 'edges']
 * ```
 */
export function publishedDesignSchema(): JsonObject {
  const generated = z.toJSONSchema(designSchema, { io: PUBLISHED_IO });

  // Round-tripped through JSON deliberately. What is published is a JSON
  // document, and this is what makes the value in memory identical to the one
  // written to `public/design.schema.json` rather than merely similar to it —
  // which is the comparison the drift test makes.
  return JSON.parse(JSON.stringify(generated)) as JsonObject;
}

/**
 * Every field of a design, in reading order, as the `/schema` page lists them.
 *
 * The path, the type, whether it is required and what is allowed in it all come
 * out of the generated document, so the page cannot describe a field the schema
 * does not have or miss one it does. Only the meaning is written by hand.
 *
 * @returns one row per field, parents before their children
 * @throws {Error} if a field has no meaning, or a meaning names no field
 *
 * @example
 * ```typescript
 * designFields()[0]; // { path: 'title', type: 'string', isRequired: true, … }
 * ```
 */
export function designFields(): readonly DesignField[] {
  const found = fieldsIn(publishedDesignSchema(), '');
  const described = new Set(Object.keys(FIELD_MEANINGS));

  const fields = found.map((field) => {
    const meaning = FIELD_MEANINGS[field.path];

    if (meaning === undefined) {
      throw new Error(`The schema has a "${field.path}" field that nothing explains.`);
    }

    described.delete(field.path);

    return { ...field, meaning };
  });

  if (described.size > 0) {
    throw new Error(`No field of a design is called "${[...described][0]}".`);
  }

  return fields;
}

/** One field, before its meaning is looked up. */
type SchemaField = Omit<DesignField, 'meaning'>;

/**
 * Every field an object schema names, and every field of anything it holds.
 *
 * Recursive rather than written out, so a schema that grows a third list does
 * not need this walk changed. It terminates on any schema with no `properties`,
 * which is every string in the document.
 */
function fieldsIn(schema: JsonObject, prefix: string): readonly SchemaField[] {
  const required = new Set(textsAt(schema, 'required'));

  return Object.entries(objectAt(schema, 'properties')).flatMap(([name, property]) => {
    const field = asObject(property);
    const path = `${prefix}${name}`;

    return [
      { path, type: typeOf(field), isRequired: required.has(name), rule: ruleOf(field) },
      ...fieldsIn(itemsOf(field), `${path}[].`),
    ];
  });
}

/** The schema of one entry of an array, or an empty schema for anything else. */
function itemsOf(schema: JsonObject): JsonObject {
  return textAt(schema, 'type') === 'array' ? asObject(schema.items) : {};
}

/** A field's type as a reader says it: `string`, or `array of objects`. */
function typeOf(schema: JsonObject): string {
  const type = textAt(schema, 'type');

  if (type !== 'array') {
    return type;
  }

  const entry = textAt(itemsOf(schema), 'type');

  return entry === '' ? 'array' : `array of ${entry}s`;
}

/** What the published document allows in one field, as a sentence. */
function ruleOf(schema: JsonObject): string {
  if (textAt(schema, 'type') === 'array') {
    return numberAt(schema, 'minItems') === undefined
      ? 'Any number of entries, including none.'
      : `At least ${numberAt(schema, 'minItems')} entries.`;
  }

  const holdsSomething = numberAt(schema, 'minLength') === 1;
  const holdsVisibleText = textAt(schema, 'pattern') === '\\S';

  if (holdsSomething && holdsVisibleText) {
    return 'At least one character that is not a space. Spaces around the text are kept exactly as the file wrote them.';
  }

  return holdsSomething ? 'It may not be empty.' : '';
}

/**
 * The guards below are the boundary between a generated document and code that
 * reads it. Nothing here trusts a key to be there or to be the type it was last
 * time: every one answers with something usable, so a change in what Zod emits
 * shows up as a missing row the tests catch rather than as a thrown page.
 */

/** One object out of a JSON value, or an empty one for anything else. */
function asObject(value: JsonValue | undefined): JsonObject {
  if (typeof value !== 'object' || value === null || Array.isArray(value)) {
    return {};
  }

  return value as JsonObject;
}

/** The object at a key, or an empty one. */
function objectAt(schema: JsonObject, key: string): JsonObject {
  return asObject(schema[key]);
}

/** The string at a key, or an empty one. */
function textAt(schema: JsonObject, key: string): string {
  const value = schema[key];

  return typeof value === 'string' ? value : '';
}

/** The number at a key, or nothing, which is not the same as zero. */
function numberAt(schema: JsonObject, key: string): number | undefined {
  const value = schema[key];

  return typeof value === 'number' ? value : undefined;
}

/** The strings in the array at a key, ignoring anything that is not one. */
function textsAt(schema: JsonObject, key: string): readonly string[] {
  const value = schema[key];

  if (!Array.isArray(value)) {
    return [];
  }

  return value.flatMap((entry) => (typeof entry === 'string' ? [entry] : []));
}
